### ISSUE TITLE
Missing Files in Provided Documentation

### ISSUE THREAD

**Issue by guangxiache** [huaishengzhu/3MDiffusion#3]
Hi ,

I hope this message finds you well. I have been using your repository and found it extremely helpful. However, I noticed that some files mentioned in the documentation seem to be missing. Could you please check and update the repository with the missing files?

Thank you for your assistance!

Best regards

![20241224225231](https://github.com/user-attachments/assets/eab86090-c338-451b-9ed8-d82216eba3d6)

**Comment by huaishengzhu** [comment]
Hi,

Thanks for your interest of our work! lavis and pytorch_lightning are packages which can be downloaded from the website. You can just follow our environment preparation step to achieve these packages.

Best,

Huaisheng
